import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { poppins } from "./fonts";
import { ThemeProvider } from "@/components/theme-provider";
import ReactQuery from "@/providers/react-query";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "delicious",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <ReactQuery>
          <body className={`${poppins.className}`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </body>
        </ReactQuery>
      </html>
    </ClerkProvider>
  );
}
